---
title: "Model Description"
author: "Adam Reimer"
date: "September 4, 2018"
output: 
  bookdown::word_document2
---

```{r setup, include=FALSE}
library(bookdown)
knitr::opts_chunk$set(echo = TRUE)
```

##State-Space Model
The state-space model (Appendix A1) specifies how population parameters lead to the data that are observed. The process model component describes how natural population processes generate true annual abundance by age, and the observation model component describes how the observed data are generated.
  
###Notation conventions
Many parameters are estimated in this model. Parameters with similar function or interpretation often use the same symbol, distinguished by a subscripted capital letter. Subscripted lower case letters denote parameter indices. For example, all harvest rates use the symbol $\mu$ where $\mu_{By}$ is the harvest rate below (downstream of) Susitna RM 34 and Yenta RM 6 in year $y$, $\mu_{Ays}$ is the harvest rate of stock $s$ above Susitna RM 34 and Yenta RM 6 in year $y$, and $\mu_{Dy}$ is the harvest rate upstream of the Deshka River weir in year $y$. Year indices run from 1 to 39 representing 1979 to 2017 respectively. Stock indices run from 1 to 5 representing Deshak River, Eastside Susitna Drainage, Talkeetna River, Yentna River, and all 5ther areas respectively.
  
###Process Component
Abundance of Susitna River Chinook salmon in each stock group is generated by a spawner-recruit (SR) relationship, which describes the number of fish expected to return (the “recruitment”) from a given “escapement” (number of spawning fish). The total recruitment $R_{ys}$ produced from fish spawning in year $y$ by stock $s$ follows the Ricker (1975) formulation:
\begin{equation}
R_{ys}~=~S_{ys}\alpha_s exp(\beta_s S_{ys})
  (\#eq:ricker)
\end{equation}
where $S_{ys}$ is the number of spawners, $\alpha_s$ (number of recruits per spawner in the absence of density dependence) is a measure of productivity for each stock group, and $\beta_s$ is a measure of density dependence for each stock group.

Productivity varies among brood years, fluctuating around a central tendency. Time-varying productivity often manifests as serially correlated model residuals, so a lognormal error term with a lag of one year (MA1) was included in the linearized form of the spawner-recruit relationship (Noakes et al. 1987)
\begin{equation}
ln(R_{ys})~=~ln(S_{ys})+ln(\alpha_s)-\beta_s S_{ys} +\phi_s \nu_{(y-1)s}+\epsilon_{Ws}
  (\#eq:rickerar)
\end{equation}
where $\phi_s$ is the lag-1 moving average coefficient, $\nu_{ys}$ are model residuals
\begin{equation}
\nu_{ys}~=~ln(R_{ys})-ln(S_{ys})-ln(\alpha_s)+\beta_s S_{ys} 
  (\#eq:residuals)
\end{equation}
and the $\epsilon_{Ws}$ are independently and normally distributed process errors with “white noise” variance $\sigma^2_{Ws}$. The productivity parameters for each stock $\alpha_s$ are drawn from a common distribution, $\textrm{ln}(\alpha_s)~\sim~\textrm{Normal}(\mu_\alpha, \sigma^2_\alpha)$.  
  
Expected age at maturity is allowed to trend through time and fluctuate annually. Age-at-maturity vectors $\mathbf{p_y} = (\begin{array}{am} p_{y3} & p_{y4} & p_{y5} & p_{y6} \end{array})$ from year $y$ returning at ages 3-6 were drawn from a $Dirichlet(\gamma_{y3}, \gamma_{y4},  \gamma_{y5}, \gamma_{y6})$ distribution. The Dirichlet parameters are expressed in an alternate form where 
\begin{equation}
D~=~\sum_{a=3}^6 \gamma_{ya}
   (\#eq:Dage)
\end{equation}
is the (inverse) dispersion of the annual age-at-maturity vectors, reflecting consistency of age at maturity among brood years.
The location parameters
\begin{equation}
\pi_{ya}~=~\frac{\gamma_{ya}}{D}~=~\frac{exp(ML1_a+ML2_ay)}{\sum_a exp(ML1_a+ML2_ay)}
   (\#eq:pi)
\end{equation}
are proportions that sum to one and reflect age-at-maturity central tendency in each year where $ML1_a$ and $ML2_a$ are multinomial logistic regression coefficients describing trending age at maturity.
  
The abundance $N_{yas}$ in stock group $s$ of age $a$ Chinook salmon in calendar year $y$ is the product of the age at maturity scalar $p_{ya}$ and the total return (recruitment) $R_{ys}$ in stock group $s$ from year $y−a$:
\begin{equation}
N_{yas}~=~p_{(y-a)a}R_{(y-a)s}
   (\#eq:Ntas)
\end{equation}
Total run $N_{ys}$ for stock group $s$ during calendar year $y$ is the sum of abundance at age across ages:
\begin{equation}
N_{ys}~=~\sum_{a=3}^6 N_{yas}
   (\#eq:Nts)
\end{equation}
Annual harvest of Susitna-origin Chinook salmon below (downstream of) Susitna RM 34 and Yenta RM 6, $H_{By}$, was modeled as the product of the annual harvest rate below in the area $\mu_{By}$ and total run $N_y$:
\begin{equation}
H_{By}~=~\mu_{By}\sum_{s=1}^5 N_{ys}
   (\#eq:Hbelow)
\end{equation}
Inriver run $IR_{ys}$ of stock group $s$ during calendar year $y$ at Susitna RM 34 and Yenta RM 6 was modeled as the product of stock specific total run $N_{ys}$ and the annual survival rate in the area downstream: 
\begin{equation}
IR_{ys}~=~N_{ys}(1-\mu_{By})
   (\#eq:IR)
\end{equation}
Annual harvest of stock group $s$ above Susitna RM 34 and Yenta RM 6 $H_{Ays}$ was the product of the annual harvest rate for each stock in the area $\mu_{Ays}$ and inriver run:
\begin{equation}
H_{Ays}~=~\mu_{Ays}IR_{ys}
   (\#eq:Habove)
\end{equation}
Annual harvest of Deshka River Chinook salmon (stock = 1) upstream of the Deshka River weir $H_{Dy}$ was the product of the annual harvest rate the above the weir $\mu_{Dy}$ and abundance of Chinook salmon at the weir $IR_{Dy}$:
\begin{equation}
H_{Dy}~=~\mu_{Dy}IR_{Dy}~=~\mu_{Dy}(IR_{y1} - H_{Ay1})
   (\#eq:Hdeshka)
\end{equation}
Finally, spawning escapement $S_{ys}$ was inriver run abundance minus harvest above Susitna RM 34 and Yenta RM 6:
\begin{equation}
S_{y1}~=~IR_{Dy}-H_{Dy}~=~IR_{y1} - H_{Ay1} - H_{Dy}
   (\#eq:S1)
\end{equation}
for the Deshka River stock group and
\begin{equation}
S_{y(2:5)}~=~IR_{y(2:5)}-H_{Ay(2:5)}
   (\#eq:S2)
\end{equation}
for the other stock groups.
  
Multiple tributaries ($t=1,2,\dots,T$) contribute to the spawning escapement in the Eastside, Talkeetna, Yentna and Other stock groups. Expected stock composition of the $T-1$ tributaries which are monitored by aerial survey is allowed to trend through time and fluctuate annually. Four sets of equations analogous to eq. $\@ref(eq:Dage)$ and eq. $\@ref(eq:pi)$ were used to define stock composition vectors $\mathbf{\rho^*}_{sy} = (\begin{array} \rho^*_{sy1} & \rho^*_{sy2 }& \dots & \rho^*_{sy(T-1)}\end{array})$ for the surveyed tributaries in each stock group.
  
###Observation Component
Observed data (Appendices B1-B#) include estimates of annual harvest below and above Susitna RM 34 and Yenta RM 6, age composition data from carcass surveys, creel surveys, fishwheel catches and weir projects throughout the Susitna drainage, weir counts for 3 tributaries, single aerial survey data for 16 tributaries, mark-recapture estimates of inriver run, radio telemetry data, and length composition data. Sampling distributions for the data follow.
  
Estimated annual inriver runs of Chinook salmon from mark-recapture $\widehat{IR}_{ys}$ for stock $s$ were
\begin{equation}
\widehat{IR}_{ys}~=~IR_{500ys}exp(\epsilon_{IRys})
   (\#eq:IRhat)
\end{equation}
where $IR_{500ys}$ is the inriver run of fish 500mm MEFT or larger and $\epsilon_{IRys}~\sim~\textrm{Normal}(0, \sigma^2_{IRys})$ with
\begin{equation}
\sigma^2_{IR_{ys}}~=~\textrm{ln}(\textrm{CV}(\widehat{IR}_{ys})^2+1)
   (\#eq:cvIR)
\end{equation}

The number of age-3 and age-4 fish that were less than 500mm MEFT $x_{500ya}$ in year $y$ were
\begin{equation}
x_{500ya}~\sim~\textrm{Binomial}(p_{500ya}, n_{500ya})
   (\#eq:xsmall)
\end{equation}
where $n_{500ya}$ is the  total number of fish sampled for age and length in age class $a$ during year $y$ and $p_{500ya}$ is the proportion of fish less than 500mm MEFT in age class $a$ during year $y$. Inriver runs of fish 500mm MEFT or greater $IR_{500ys}$ were
\begin{equation}
IR_{500ys}~=~IR_{ys}[1-(q_{y3}p_{500y3}+q_{y4}p_{500y4})]
   (\#eq:IRlarge)
\end{equation}
where $q_{ya}$ is the proportion of the run that is age $a$ in calendar year $y$.
  
Estimated annual harvest of Susitna River Chinook salmon below Susitna RM 34 and Yenta RM 6 $\widehat{H}_{By}$ was
\begin{equation}
\widehat{H}_{By}~=~H_{By}exp(\epsilon_{HBy})
   (\#eq:HBhat)
\end{equation}
where the $\epsilon_{HBy}~\sim~\textrm{Normal}(0, \sigma^2_{HBy})$ and the variances followed eq. $\@ref(eq:cvIR)$ with an assumed CV of 0.05 reflecting good precision associated with reported commercial and subsistence harvest.
  
Estimated annual harvest of Susitna River Chinook salmon above Susitna RM 34 and Yenta RM 6 $\widehat{H}_{Ays}$ for stock $s$ was
\begin{equation}
\widehat{H}_{Ays}~=~H_{Ays}exp(\epsilon_{HAy})
   (\#eq:HAhat)
\end{equation}
where the $\epsilon_{HAy}~\sim~\textrm{Normal}(0, \sigma^2_{HAy})$ and the variances followed eq. $\@ref(eq:cvIR)$ with an assumed CV of 0.2 reflecting moderate precision associated with estimated harvest.

Estimated annual harvest of Deshka River Chinook upstream of the Deshka weir $\widehat{H}_{Dy}$ was
\begin{equation}
\widehat{H}_{Dy}~=~H_{Dy}exp(\epsilon_{HAy})
   (\#eq:HAhat)
\end{equation}
with an assumed CV of 0.2 reflecting moderate precision associated with estimated harvest.

Radio telemetry final destinations within each stock group $\mathbf{r}_{sy} = (\begin{array}{am} r_{sy1} & r_{sy2} & \dots & r_{syT} \end{array})$ were partitioned into $T$ categories with $T-1$ categories representing tributaries within the stock group that are counted during aerial surveys and one category ($T$) representing all tributaries that were not counted during aerial surveys. Radio tags located in tributaries that were not counted during aerial surveys were
\begin{equation}
r_{syT}~\sim~\textrm{Binomial}\left(\rho\prime_{sy}, \sum_t^T r_{syt}\right)
   (\#eq:nosurvey)
\end{equation}
where $\rho\prime_{sy}$ estimates the annual proportion of radio tagged fish from stock $s$ that spawned in tributaries that were not monitored by aerial survey. Equations analogous to eq. $\@ref(eq:Dage)$ and eq. $\@ref(eq:pi)$ (without the regression component) were used to define the prior structure on $\rho\prime_{sy}$.
  
Radio tags located within within tributaries that were counted during aerial surveys $r_{sy[1:(T-1)]}$ were:
\begin{equation}
r_{sy[1:(T-1)]}~\sim~\textrm{Multinomial}\left(\rho^*_{syt}, \sum_t^{T-1} r_{syt}\right)
   (\#eq:survey)
\end{equation}
where $\rho^*_{syt}$ estimates the annual proportion of radio tagged fish from stock $s$ that spawned in tributary $t$.
  
Stock composition was calculated as:
\begin{equation}
\rho_{syt}~=~\left(\begin{array}{} \rho^*_{sy1}(1-\rho\prime_{sy}) & \rho^*_{sy2}(1-\rho\prime_{sy}) & \dots & \rho\prime_{sy} \end{array}\right)
   (\#eq:pcomp)
\end{equation}

The proportion of the spawning escapement counted during single aerial surveys $\theta_t$ was
\begin{equation}
\textrm{logit}(\theta_t)~\sim~\textrm{Normal}(\mu_\theta, \sigma^2_\theta)
   (\#eq:theta)
\end{equation}

Annual single aerial surveys $as_{yt}$ were available for sixteen tributaries $t$. Each survey is related to abundance for the stock group within which it was located:
\begin{equation}
as_{yt}~=~\theta_t\rho_{syt}S_{ys}exp(\epsilon_{ASt})
   (\#eq:as)
\end{equation}
where the $\epsilon_{ASt}~\sim~\textrm{Normal}(0, \sigma^2_{ASt})$ and $\sigma_{ASt}~\sim~\textrm{half_Cauchy}(0, B_{AS})$ where $B_{AS}$ is the median of the distribution of $\sigma_{ASt}$.
  
Weirs counts were available for three tributaries. Each weir count is related to abundance for the stock group within which it was located:
\begin{equation}
w_{yt}~=~\rho_{syt}S_{ys}exp(\epsilon_W)
   (\#eq:weir)
\end{equation}
where the $\epsilon_W~\sim~\textrm{Normal}(0, \sigma_W^2)$ and the variances followed eq. $\@ref(eq:cvIR)$ with an assumed CV of 0.05 reflecting good precision associated with weir counts.
  
The scale-age counts $x_{yac}$ were modeled as multinomially distributed 
\begin{equation}
x_{yac}~=~\textrm{Multinomial}\left(q^*_{yac}, \sum_{(a=3)}^6 x_{yac}\right)
   (\#eq:xage)
\end{equation}
The location parameters are
\begin{equation}
q^*_{yac}~=~\frac{exp\left[\textrm{ln}\left(\frac{N_{ya}}{N_{y(a=3)}}\right)+b1_a I1+b2_a I2+b3_a I3\right]}{\sum_a exp\left[\textrm{ln}\left(\frac{N_{ya}}{N_{y(a=3)}}\right)+b1_a I1+b2_a I2+b3_a I3\right]}
   (\#eq:qstar)
\end{equation}
which represents a multinomial logistic regression where the intercept is a function of annual abundance in each age class and the categorical covariates account for age-related sampling bias. The parameters $b1$ to $b3$ represent bias adjustments for weir, creel and carcass survey/fishwheel samples respectively while covariates $I1$ to $I3$ represent indicator variables for each sample type. Because $b1=0$ weir samples are considered unbiased and estimated annual age composition is:
\begin{equation}
q_{yt}~=~\frac{N_{ya}}{\sum_{a=3}^6 N_{y}}
   (\#eq:qstar)
\end{equation}

##Model Fitting
Model fitting involves finding the values of the population parameters that could have plausibly resulted in the data that were observed. To do so, Markov Chain Monte Carlo (MCMC) methods were employed using the package RJAGS (Plummer 2013) within R (R Core Team 2016). This methodology allows for inclusion of the effects of measurement error, serially-correlated productivity, and missing data into the analysis and provides a more realistic assessment of uncertainty than is possible with classical statistical methods. By properly specifying process variation, measurement error, and time-dependent linkage in the model, biases in the estimates can be reduced (Su and Peterman 2012).
  
Bayesian statistical methods employ the language of probability to quantify uncertainty about model parameters. Knowledge existing about the parameters outside the framework of this analysis is the “prior” probability distribution. The output of the Bayesian analysis is called the “posterior” probability distribution, which is a synthesis of the prior information and the information contained in the data. See Fleischman et al. (2013) and Staton et al. (2016) for similar applications of the methods used in this report. 
  
###Prior Distributions
Noninformative priors (chosen to have minimal effect on the posterior) were used for most parameters. Initial recruitments $R_{1973}-R_{1978}$ (those lacking linked spawner abundance) were modeled as drawn from a common lognormal distribution with median $\mu_{logR}$ and variance $\sigma^2_{logR}$. Truncated normal priors with mean zero, very large variances, and constrained to be positive were used for $\mu_{log(\alpha)}$, $\beta$, $\mu_{logR}$, . Initial model residual $\nu_s$ were given a truncated normal prior with mean zero and variance $\sigma^2_{Ws}/(1-\phi^2_s)$ between -3 and 3. Annual harvest rates ($\mu_{By}, \mu_{Asy}, \mu_{Dy}$) were given $\textrm{beta}(0.5,0.5)$ priors. Diffuse conjugate inverse gamma priors were used for $\sigma^2_{Ws}, \sigma^2_{logR}$. Dirichlet dispersion parameters $1/\sqrt{D}$ for age and stock composition have $\textrm{Uniform}(0.1,1)$ priors. $B_{AS}$, $p_{500y3}$ and $p_{500y4}$ have $\textrm{Uniform}(0,1)$ priors.
  
###Sampling from the Posterior Distribution
MCMC samples were drawn from the joint posterior probability distribution of all unknowns in the model. Three chains were initiated, the first 50,000 samples from each were discarded and 2,000,000 additional samples were generated. After thinning by a factor of 200, the remaining 2,250 samples were used to estimate the marginal posterior means, standard deviations, and percentiles. The diagnostic tools of RJAGS (Plummer 2013) and ShinySTAN (Stan Development Team 2016) were used to assess mixing and convergence, and no major problems were encountered. Interval estimates were constructed from the percentiles of the posterior distribution.

##Reference Points and Optimal Yield Profiles
Reference points were calculated for each individual MCMC sample. Spawning abundance providing maximum sustained yield (MSY) $S_{MSY}$ was approximated
\begin{equation}
S_{MSYs}~\cong~\frac{\textrm{ln}(\alpha'_s)}{\beta}[0.5-0.07\textrm{ln}(\alpha'_s)]
   (\#eq:SMSY)
\end{equation}
Sustained yield at a specified level of $S$ was obtained by subtracting spawning escapement from recruitment:
\begin{equation}
Y_{Ss}~=~R_s-S_s~=~S_{s}exp(\textrm{ln}(\alpha'_s)-\beta_s S_{s})-S_s
   (\#eq:Ys)
\end{equation}
Other relevant quantities include harvest rate leading to maximum sustained yield, approximated by (Hilborn 1985)
\begin{equation}
U_{MSYs}~\cong~\textrm{ln}(\alpha'_s)[0.5-0.07\textrm{ln}(\alpha'_s)]
   (\#eq:UMSY)
\end{equation}
escapement leading to maximum sustained recruitment (MSR)
\begin{equation}
S_{MSRs}~=~\frac{1}{\beta_s}
   (\#eq:SMSR)
\end{equation}
and equilibrium spawning abundance, where recruitment exactly replaces spawners:
\begin{equation}
S_{EQs}~=~\frac{\textrm{ln}(\alpha'_s)}{\beta_s}
   (\#eq:SEQ)
\end{equation}
The quantity
\begin{equation}
\textrm{ln}(\alpha'_s)~=~\textrm{ln}(\alpha_s)+\frac{\sigma^2_{Ws}}{2(1-\phi_s^2)}
   (\#eq:alphaprime)
\end{equation}
in Equations $\@ref(eq:SMSY)$, $\@ref(eq:Ys)$, $\@ref(eq:UMSY)$, and $\@ref(eq:SEQ)$ adjusts for the difference between the median and the mean of a right-skewed lognormal error distribution autocorrelation.

The probability that a given spawning escapement $S$ would produce average yields exceeding X% of MSY was obtained by calculating $Y_S$ at incremental values of $S$ for each MCMC sample, then comparing $Y_S$ with X% of the value of MSY for that sample. The proportion of samples in which $Y_S$ exceeded X% of MSY is an estimate of the desired probability, and the plot of proportion versus $S$ is termed an optimal yield profile (OYP; Fleischman et al. 2013).

The probability that yield would be reduced to less than X% of MSY by supplying too few spawners $S$ was obtained by calculating $Y_S$ at incremental values of $S$ and tallying the number of MCMC samples for which $Y_S$ was less than X% of MSY and $S$ was less than $S_{MSY}$. A plot of the fraction of samples in which this condition occurred versus $S$ is termed an overfishing profile (Bernard and Jones III 2010).

The probability that a given spawning escapement $S$ would produce average recruitments $R$ exceeding X% of MSR was obtained by calculating $R$ (Equation 1) at incremental values of $S$ for each MCMC sample, then comparing $R$ with X% of the value of MSR for that sample. The proportion of samples in which $R$ exceeded X% of MSR is an estimate of the desired probability, and the plot of the proportion versus $S$ is termed an optimal recruitment profile (ORP; Fleischman et al. 2013).

OYPs Overfishing profiles and ORPs were used to quantify the yield (or recruitment) performance of prospective escapement goals, taking into consideration the uncertainty about the true abundance, productivity, and capacity of the stock.

##Escapement Goals Standardized To $S_{MSY}$
For purposes of comparing escapement goals across stocks, we divided the lower and upper bounds of 21 published goals for Alaska Chinook salmon (Munro and Volk 2016) by point estimates of $S_{MSY}$ for each stock, thereby expressing all goal ranges in terms of multiples of $S_{MSY}$. These values were multiplied by estimates of $S_{MSY}$ for each stock group to provide a graphical comparison of the recommended goals with those from other stocks.

##Escapement Goal Review Process
An interdivisional escapement goal review team was convened to review the available data, discuss analyses and results, and make escapement goal recommendations. The escapement goals recommended in this report are the product of several collaborative meetings of the review team and other ADF&G staff. The final recommendation was reached by consensus of fisheries scientists and regional research coordinators from both fisheries divisions.

