---
title: "Model Description"
author: "Adam Reimer"
date: "September 4, 2018"
output: 
  bookdown::word_document2: 
    reference_docx: style.docx
---

```{r setup, include=FALSE}
library(bookdown)
knitr::opts_chunk$set(echo = TRUE)
```

##State-Space Model
The state-space model (Appendix A1) specifies how population parameters lead to the data that are observed. The process model component describes how natural population processes generate true annual abundance by age, and the observation model component describes how the observed data are generated.

###Process Component
Abundance of Susitna River Chinook salmon in each stock group is generated by a spawner-recruit (SR) relationship, which describes the number of fish expected to return (the “recruitment”) from a given “escapement” (number of spawning fish). The total recruitment $R$ produced from fish spawning in year $y$ by stock $s$ follows the Ricker (1975) formulation:
\begin{equation}
R_{ys}~=~S_{ys}\alpha_s exp(\beta_s S_{ys})
  (\#eq:ricker)
\end{equation}
where $S_{ys}$ is the number of spawners, parameter $\alpha_s$ (number of recruits per spawner in the absence of density dependence) is a measure of productivity for each stock group, and parameter $\beta_s$ is a measure of density dependence for each stock group.

In the model, productivity is allowed to vary among brood years, fluctuating around a central tendency. Time-varying productivity often manifests as serially correlated model residuals, so an lognormal error term with a lag of one year (MA[1]) was included in the linearized form of the spawner-recruit relationship (Noakes et al. 1987)
\begin{equation}
ln(R_{ys})~=~ln(S_{ys})+ln(\alpha_s)-\beta_s S_{ys} +\phi_s \nu_{y-1}+\epsilon.w_{s}
  (\#eq:rickerar)
\end{equation}
where $\phi$ is the lag-1 moving average coefficient, $\nu_y$ are model residuals
\begin{equation}
\nu_{ys}~=~ln(R_{ys})-ln(S_{ys})-ln(\alpha_s)+\beta_s S_{ys} 
  (\#eq:residuals)
\end{equation}
and the $\epsilon.w_{y}$ are independently and normally distributed process errors with “white noise” variance $\sigma.w^2$. The natural log of the productivity parameter for each stock is drawn from a normal distribution $\textrm{ln}(\alpha_s)~\sim~\textrm{Normal}(\mu.alpha, \sigma.alpha)$.  

Expected age at maturity is allowed to trend through time and fluctuate annually. Age-at-maturity vectors $\mathbf{p_y} = (\begin{array}{am} p_{y3} & p_{y4} & p_{y5} & p_{y6} \end{array})$ from year $y$ returning at ages 3-6 were drawn from a $Dirichlet(\gamma_{y3}, \gamma_{y4},  \gamma_{y5}, \gamma_{y6})$ distribution. The Dirichlet parameters are expressed in an alternate form where 
\begin{equation}
D~=~\sum_{a=3}^6 \gamma_{ya}
   (\#eq:Dage)
\end{equation}
is the (inverse) dispersion of the annual age-at-maturity vectors, reflecting consistency of age at maturity among brood years.
The location parameters are
\begin{equation}
\pi_{ya}~=~\frac{\gamma_{ya}}{D}~=~\frac{exp(ML1_a+ML2_a\times y)}{\sum_a exp(ML1_a+ML2_a\times y)}
   (\#eq:pi)
\end{equation}
The abundance $N_{yas}$ in stock group $s$ of age $a$ Chinook salmon in calendar year $y$ is the product of the age proportion scalar $p$ and the total return (recruitment) $R_$ in stock group $s$ from year $y−a$:
\begin{equation}
N_{yas}~=~p_{(y-a)a}R_{(y-a)s}
   (\#eq:Ntas)
\end{equation}
Total run $N$ for stock group $s$ during calendar year $y$ is the sum of abundance at age across ages:
\begin{equation}
N_{ys}~=~\sum_{a=3}^6 N_{yas}
   (\#eq:Nts)
\end{equation}
Annual harvest of Susitna-origin Chinook salmon below (downstream of) Susitna RM 34 and Yenta RM 6 $H.below$ was modeled as the product of the annual harvest rate below in the area and total run:
\begin{equation}
H.below_y~=~\mu.below_y\sum_{s=1}^5 N_{ys}
   (\#eq:Hbelow)
\end{equation}
Inriver run $IR$ of stock group $s$ during calendar year $y$ at Susitna RM 34 and Yenta RM 6 was modeled as follows: 
\begin{equation}
IR_{ys}~=~N_{ys}(1-\mu.below_y)
   (\#eq:IR)
\end{equation}
Annual harvest of stock group $s$ above Susitna RM 34 and Yenta RM 6 $H.above$ was the product of the annual harvest rate for each stock in the area and inriver run abundance:
\begin{equation}
H.above_{ys}~=~\mu.above_{ys}IR_{ys}
   (\#eq:Habove)
\end{equation}
Finally, spawning escapement $S$ was inriver run abundance minus harvest above Susitna RM 34 and Yenta RM 6:
\begin{equation}
S_{ys}~=~IR_{ys}-H.above_{ys}
   (\#eq:S)
\end{equation}
Multiple tributaries $t=1,2,\dots,T$ contribute to the spawning escapement in some stock groups. Expected stock composition is allowed to trend through time and fluctuate annually. Stock composition vectors $\mathbf{p.s_y} = (\begin{array}{am} p.s_{y1} & p.s_{y2} & \dots & p.s_{y(T-1)} \end{array})$ from year $y$ were drawn from a $Dirichlet(\gamma.s_{y1}, \gamma.s_{y2},  \dots, \gamma.s_{y(T-1)})$ distribution. The Dirichlet parameters are expressed in an alternate form where 
\begin{equation}
D.s~=~\sum_{t=1}^{(T-1)} \gamma.s_{yt}
   (\#eq:DS)
\end{equation}
is the (inverse) dispersion of the annual stock composition vectors, reflecting consistency of stock composition among calendar years.
The location parameters are
\begin{equation}
\pi.s_{yt}~=~\frac{\gamma.s_{yt}}{D.s}~=~\frac{exp(ML1.s_t+ML2.s_t\times y)}{\sum_a exp(ML1.s_t+ML2.s_t\times y)}
   (\#eq:pis)
\end{equation}
  
###Observation Component
Observed data (Appendices B1-B#) include estimates of annual harvest below and above Susitna RM 34 and Yenta RM 6, age composition data from carcass surveys, creel surveys, fishwheel catches and weir projects throughout the Susitna drainage, single aerial survey data for 16 tributaries, MR estimates of inriver run, radio telemetry data, and length composition data. Sampling distributions for the data follow.
  
Estimated inriver runs of Chinook salmon from mark-recapture were
\begin{equation}
\widehat{IR}_{ys}~=~IR.500_{ys}exp(\epsilon_{IRys})
   (\#eq:IRhat)
\end{equation}
where the $\epsilon_{IRys}~\sim~\textrm{Normal}(0, \sigma^2_{IRys})$ and
\begin{equation}
\sigma^2_{IR_{ys}}~=~\textrm{ln}(\textrm{CV}(\widehat{IR}_{ys})^2+1)
   (\#eq:cvIR)
\end{equation}
The number of age-3 and age-4 fish that were less than 500mm MEFT were
\begin{equation}
x.small_a~=~\textrm{Binomial}(p.small_a, n.small_a)
   (\#eq:xsmall)
\end{equation}
so that inriver runs of fish 500 mm MEFT or greater $IR.500_{ys}$ were
\begin{equation}
IR.large_{ys}~=~IR_{ys}(1-q_{y3}p.small_{y3})(1-q_{y4}p.small_{y4})
   (\#eq:IRlarge)
\end{equation}
where $q_{ya}$ is the proportion of the run that is age $a$ in calendar year $y$.
Estimated annual harvest of Susitna River Chinook salmon below Susitna RM 34 and Yenta RM 6 was
\begin{equation}
\widehat{H.below}_y~=~H.below_yexp(\epsilon_{HBy})
   (\#eq:Hbelowhat)
\end{equation}
where the $\epsilon_{HB_y}~\sim~\textrm{Normal}(0, \sigma^2_{HB_y})$ and the variances followed Equation $\@ref(eq:cvIR)$ with an assumed CV of 0.05 reflecting reported commercial and subsistence harvest.

Estimated annual harvest of Susitna River Chinook salmon above Susitna RM 34 and Yenta RM 6 was
\begin{equation}
\widehat{H.above}_{ys}~=~H.above_{ys}exp(\epsilon_{HAys})
   (\#eq:Habovehat)
\end{equation}
where the $\epsilon_{HA_y}~\sim~\textrm{Normal}(0, \sigma^2_{HAy})$ and the variances followed Equation $\@ref(eq:cvIR)$ with an assumed CV of 0.2 reflecting estimated harvest.

Single aerial surveys were available for sixteen tributaries. Each comprised an independent measure of relative abundance for the stock group within which it was located:
\begin{equation}
a_{yt}~=~\theta_tp.comp_{yt}S_{ys}exp(\epsilon.survey_t)
   (\#eq:as)
\end{equation}
where the $\epsilon.survey_t~\sim~\textrm{Normal}(0, \sigma.survey^2_t)$ and $\sigma.survey_t~\sim~\textrm{half_Cauchy}(0, B)$ where $B$ is the median of the distribution of $\sigma.survey_t$.

Radio telemetry final destinations within each stock group $\mathbf{r.s_y} = (\begin{array}{am} r.s_{y1} & r.s_{y2} & \dots & r.s_{yT} \end{array})$ were partitioned into $T$ categories with $T-1$ categories representing tributaries within the stock group that are counted during aerial surveys and one category representing all tributaries that were not counted during aerial surveys. Fish within tributaries that were not counted during aerial surveys were
\begin{equation}
r.s_{yT}~\sim~\textrm{Binomial}(p.noair_y, \sum_t^T r.s_{yt})
   (\#eq:nosurvey)
\end{equation}
Fish within tributaries that were counted during aerial surveys were
\begin{equation}
r.s_{y[1:(T-1)]}~\sim~\textrm{Multinomial}(p.air_{yt}, \sum_t^{T-1} r.s_{yt})
   (\#eq:nosurvey)
\end{equation}
Stock composition was calculated as
\begin{equation}
p.comp_{yt}~=~(\begin{array}{} p.air_{y1}(1-p.noair_y) & p.air_{y2}(1-p.noair_y) & \dots & p.noair_y \end{array})
   (\#eq:pcomp)
\end{equation}

The proportion of the spawning escapement counted during single aerial surveys was
\begin{equation}
\textrm{logit}(\theta_t)~\sim~\textrm{Normal}(\mu_\theta, \sigma^2_\theta)
   (\#eq:theta)
\end{equation}

Three weirs counts were available. Each comprised an independent measure of relative abundance for the stock group within which it was located:
\begin{equation}
w_{yt}~=~p.comp_{yt}S_{ys}exp(\epsilon.weir)
   (\#eq:weir)
\end{equation}
where the $\epsilon.weir~\sim~\textrm{Normal}(0, \sigma.weir^2)$.

The scale-age counts $x_{ya}$ were modeled as multinomially distributed 
\begin{equation}
x_{ya}~=~\textrm{Multinomial}\left(q^*_{ya}, \sum_{(a=3)}^6 x_{ya}\right)
   (\#eq:xage)
\end{equation}
The location parameters are
\begin{equation}
q^*_{yt}~=~\frac{exp\left[\textrm{ln}\left(\frac{N_{ya}}{N_{y(a=3)}}\right)+b_{ca}\right]}{\sum_a exp\left[\textrm{ln}\left(\frac{N_{ya}}{N_{y(a=3)}}\right)+b_{ca}\right]}
   (\#eq:qstar)
\end{equation}
where $b_{ca}$ is a bias correction for the type of age sample $c$. Estimated annual age composition is then
\begin{equation}
q_{yt}~=~\frac{N_{ya}}{\sum_(a=3)^6 N_{y}}
   (\#eq:qstar)
\end{equation}

##Model Fitting

###Prior Distributions

###Sampling from the Posterior Distribution

##Reference Points and Optimal Yield Profiles
Reference points were calculated for each individual MCMC sample. Spawning abundance providing maximum sustained yield (MSY) $S_{MSY}$ was approximated
\begin{equation}
S_{MSYs}~\cong~\frac{\textrm{ln}(\alpha'_s)}{\beta}[0.5-0.07\textrm{ln}(\alpha'_s)]
   (\#eq:SMSY)
\end{equation}
Sustained yield at a specified level of $S$ was obtained by subtracting spawning escapement from recruitment:
\begin{equation}
Y_{Ss}~=~R_s-S_s~=~S_{s}exp(\textrm{ln}(\alpha'_s)-\beta_s S_{s})-S_s
   (\#eq:Ys)
\end{equation}
Other relevant quantities include harvest rate leading to maximum sustained yield, approximated by (Hilborn 1985)
\begin{equation}
U_{MSYs}~\cong~\textrm{ln}(\alpha'_s)[0.5-0.07\textrm{ln}(\alpha'_s)]
   (\#eq:UMSY)
\end{equation}
escapement leading to maximum sustained recruitment (MSR)
\begin{equation}
S_{MSRs}~=~\frac{1}{\beta_s}
   (\#eq:SMSR)
\end{equation}
and equilibrium spawning abundance, where recruitment exactly replaces spawners:
\begin{equation}
S_{EQs}~=~\frac{\textrm{ln}(\alpha'_s)}{\beta_s}
   (\#eq:SEQ)
\end{equation}
The quantity
\begin{equation}
\textrm{ln}(\alpha'_s)~=~\textrm{ln}(\alpha_s)+\frac{\sigma^2_{Ws}}{2(1-\phi_s^2)}
   (\#eq:alphaprime)
\end{equation}
in Equations $\@ref(eq:SMSY)$, $\@ref(eq:Ys)$, $\@ref(eq:UMSY)$, and $\@ref(eq:SEQ)$ adjusts for the difference between the median and the mean of a right-skewed lognormal error distribution autocorrelation.

The probability that a given spawning escapement $S$ would produce average yields exceeding X% of MSY was obtained by calculating $Y_S$ at incremental values of $S$ for each MCMC sample, then comparing $Y_S$ with X% of the value of MSY for that sample. The proportion of samples in which $Y_S$ exceeded X% of MSY is an estimate of the desired probability, and the plot of proportion versus $S$ is termed an optimal yield profile (OYP; Fleischman et al. 2013).

The probability that yield would be reduced to less than X% of MSY by supplying too few spawners $S$ was obtained by calculating $Y_S$ at incremental values of $S$ and tallying the number of MCMC samples for which $Y_S$ was less than X% of MSY and $S$ was less than $S_{MSY}$. A plot of the fraction of samples in which this condition occurred versus $S$ is termed an overfishing profile (Bernard and Jones III 2010).

The probability that a given spawning escapement $S$ would produce average recruitments $R$ exceeding X% of MSR was obtained by calculating $R$ (Equation 1) at incremental values of $S$ for each MCMC sample, then comparing $R$ with X% of the value of MSR for that sample. The proportion of samples in which $R$ exceeded X% of MSR is an estimate of the desired probability, and the plot of the proportion versus $S$ is termed an optimal recruitment profile (ORP; Fleischman et al. 2013).

OYPs Overfishing profiles and ORPs were used to quantify the yield (or recruitment) performance of prospective escapement goals, taking into consideration the uncertainty about the true abundance, productivity, and capacity of the stock.

##Escapement Goals Standardized To $S_{MSY}$
For purposes of comparing escapement goals across stocks, we divided the lower and upper bounds of 21 published goals for Alaska Chinook salmon (Munro and Volk 2016) by point estimates of $S_{MSY}$ for each stock, thereby expressing all goal ranges in terms of multiples of $S_{MSY}$. These values were multiplied by estimates of $S_{MSY}$ for each stock group to provide a graphical comparison of the recommended goals with those from other stocks.

##Escapement Goal Review Process
An interdivisional escapement goal review team was convened to review the available data, discuss analyses and results, and make escapement goal recommendations. The escapement goals recommended in this report are the product of several collaborative meetings of the review team and other ADF&G staff. The final recommendation was reached by consensus of fisheries scientists and regional research coordinators from both fisheries divisions.

